#!/usr/bin/env bash
# sync-sudoers.sh — Regenerate /etc/sudoers.d/sysadmin-copilot from safety.py ALLOWED_SERVICES.
# Run as root after editing ALLOWED_SERVICES in safety.py.

set -euo pipefail

# ─── Config ───────────────────────────────────────────────────────────────────

SERVICE_USER="sysadmin-copilot"
SUDOERS_FILE="/etc/sudoers.d/sysadmin-copilot"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SAFETY_PY="${SCRIPT_DIR}/safety.py"

# ─── Colors ───────────────────────────────────────────────────────────────────

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

info()    { echo -e "${CYAN}  →${RESET} $*"; }
success() { echo -e "${GREEN}  ✓${RESET} $*"; }
warn()    { echo -e "${YELLOW}  !${RESET} $*"; }
die()     { echo -e "${RED}  ✗ ERROR:${RESET} $*" >&2; exit 1; }

# ─── Preflight ────────────────────────────────────────────────────────────────

[[ $EUID -eq 0 ]] || die "Must be run as root (sudo $0)"

[[ -f "$SAFETY_PY" ]] || die "Cannot find safety.py at ${SAFETY_PY}"

command -v python3 &>/dev/null || die "python3 is required"
command -v visudo  &>/dev/null || die "visudo is required"

SYSTEMCTL_PATH="$(command -v systemctl)" || die "systemctl not found"

# ─── Parse ALLOWED_SERVICES from safety.py ───────────────────────────────────

info "Reading ALLOWED_SERVICES from ${SAFETY_PY}..."

mapfile -t SERVICES < <(python3 - <<PYEOF
import re, sys

content = open("${SAFETY_PY}").read()
match = re.search(r'ALLOWED_SERVICES\s*=\s*\{([^}]+)\}', content, re.DOTALL)
if not match:
    sys.exit("Could not find ALLOWED_SERVICES block in safety.py")

services = sorted(re.findall(r'"([^"]+)"', match.group(1)))
if not services:
    sys.exit("ALLOWED_SERVICES appears to be empty — aborting")

print("\n".join(services))
PYEOF
)

echo ""
echo -e "${BOLD}  Services parsed from safety.py:${RESET}"
for svc in "${SERVICES[@]}"; do
    echo "    • ${svc}"
done
echo ""

# ─── Build sudoers content ────────────────────────────────────────────────────

build_alias() {
    local alias_name="$1"
    local action="$2"
    local entries=()
    for svc in "${SERVICES[@]}"; do
        entries+=("    ${SYSTEMCTL_PATH} ${action} ${svc}")
    done
    echo "Cmnd_Alias ${alias_name} = \\"
    local count="${#entries[@]}"
    local i=0
    for entry in "${entries[@]}"; do
        i=$((i + 1))
        if [[ $i -lt $count ]]; then
            echo "${entry}, \\"
        else
            echo "${entry}"
        fi
    done
}

NEW_CONTENT="$(cat <<SUDOERS
# Sysadmin Copilot — generated by sync-sudoers.sh
# Source of truth: ALLOWED_SERVICES in safety.py
# systemctl path: ${SYSTEMCTL_PATH}

$(build_alias COPILOT_RESTART restart)

$(build_alias COPILOT_STOP stop)

Cmnd_Alias COPILOT_UPDATE = \\
    /usr/bin/apt-get update, \\
    /usr/bin/apt-get upgrade -y, \\
    /usr/bin/dnf upgrade -y, \\
    /usr/bin/yum update -y, \\
    /usr/bin/snap refresh, \\
    /usr/bin/flatpak update -y

${SERVICE_USER} ALL=(ALL) NOPASSWD: COPILOT_RESTART, COPILOT_STOP, COPILOT_UPDATE
SUDOERS
)"

# ─── Show diff if file already exists ────────────────────────────────────────

if [[ -f "$SUDOERS_FILE" ]]; then
    CURRENT="$(cat "$SUDOERS_FILE")"
    if [[ "$CURRENT" == "$NEW_CONTENT" ]]; then
        success "Sudoers file is already up to date — nothing to do."
        exit 0
    fi
    echo -e "${YELLOW}  Changes to be applied:${RESET}"
    diff <(echo "$CURRENT") <(echo "$NEW_CONTENT") | sed 's/^/    /' || true
    echo ""
fi

# ─── Write, validate, apply ───────────────────────────────────────────────────

TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

echo "$NEW_CONTENT" > "$TMPFILE"
chmod 440 "$TMPFILE"

if ! visudo -c -f "$TMPFILE" &>/dev/null; then
    die "Sudoers syntax check failed — no changes made."
fi

cp "$TMPFILE" "$SUDOERS_FILE"
chmod 440 "$SUDOERS_FILE"

success "Sudoers file updated: ${SUDOERS_FILE}"
echo ""
echo -e "  Run ${BOLD}sudo visudo -c${RESET} to confirm the full sudoers config is valid."
